"""Vector Field — 2D double-vortex flow with particle streamlines.

Visualizes a velocity field generated by two counter-rotating vortices.
Arrows at grid points show the local flow direction and are color-coded by
magnitude. Particles are released and advected via RK4 integration, leaving
glowing trail paths that reveal the streamline topology.
"""
import sys, os; sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from vectormation.objects import *
import math

args = parse_args()
canvas = VectorMathAnim(verbose=args.verbose, save_dir='svgs/vector_field')
canvas.set_background()

T = 12  # total duration in seconds

# ── Double vortex field ──────────────────────────────────────────────
# Two counter-rotating vortices placed symmetrically about the center.
# V(x, y) = sum of two point-vortex contributions.
# Each vortex at position (vx, vy) with circulation G produces:
#   u = -G * (y - vy) / (2*pi*r^2)
#   v =  G * (x - vx) / (2*pi*r^2)
# We add a softening radius to avoid singularities.

# Vortex parameters (in abstract coordinates centered at (0, 0))
vortex1 = (-2.0, 0.0,  8.0)   # (x, y, circulation)
vortex2 = ( 2.0, 0.0, -8.0)   # counter-rotating

softening = 0.4  # softening radius to avoid divergence at centers

def velocity_field(x, y):
    """Compute velocity (u, v) at abstract position (x, y)."""
    u, v = 0.0, 0.0
    for vx, vy, gamma in [vortex1, vortex2]:
        dx = x - vx
        dy = y - vy
        r2 = dx * dx + dy * dy + softening * softening
        factor = gamma / (2 * math.pi * r2)
        u += -factor * dy
        v +=  factor * dx
    return u, v

# ── Coordinate mapping ──────────────────────────────────────────────
# Map abstract coords to SVG canvas (1920x1080).
# Abstract range: x in [-7, 7], y in [-4, 4] gives nice coverage.
cx, cy = 960, 540  # canvas center
scale = 120        # pixels per abstract unit

def to_svg(ax, ay):
    """Abstract (ax, ay) -> SVG (sx, sy). Note: SVG y is flipped."""
    return cx + ax * scale, cy - ay * scale

def from_svg(sx, sy):
    """SVG (sx, sy) -> abstract (ax, ay)."""
    return (sx - cx) / scale, (cy - sy) / scale

# ── Arrow grid ───────────────────────────────────────────────────────
# Place arrows at a regular grid of points, colored by velocity magnitude.
grid_x = [i * 0.9 for i in range(-7, 8)]   # 15 columns
grid_y = [j * 0.9 for j in range(-4, 5)]   # 9 rows

# Precompute velocity magnitudes for color scaling
magnitudes = []
for gx in grid_x:
    for gy in grid_y:
        u, v = velocity_field(gx, gy)
        magnitudes.append(math.sqrt(u * u + v * v))

max_mag = max(magnitudes) if magnitudes else 1.0

# Color palette: blue (slow) -> cyan -> green -> yellow -> red (fast)
palette = color_gradient(['#4444FF', '#58C4DD', '#83C167', '#FFFF00', '#FC6255'], n=256)

arrow_length = 45  # max arrow length in SVG pixels

arrows = []
for gx in grid_x:
    for gy in grid_y:
        u, v = velocity_field(gx, gy)
        mag = math.sqrt(u * u + v * v)
        if mag < 1e-6:
            continue

        # Normalize and scale arrow
        norm_mag = min(mag / max_mag, 1.0)
        arrow_len = 15 + norm_mag * (arrow_length - 15)

        # Direction unit vector
        ux, uy = u / mag, v / mag

        # SVG positions
        sx, sy = to_svg(gx, gy)
        # Arrow starts slightly behind the grid point, ends ahead
        half = arrow_len / 2
        x1 = sx - ux * half
        y1 = sy + uy * half  # flip y for SVG
        x2 = sx + ux * half
        y2 = sy - uy * half

        # Color by magnitude
        color_idx = min(int(norm_mag * 255), 255)
        color = palette[color_idx]

        arrow = Arrow(x1=x1, y1=y1, x2=x2, y2=y2,
                      stroke=color, fill=color,
                      stroke_width=2, tip_length=12, tip_width=10,
                      creation=0)
        arrow.set_opacity(0, start=0)
        arrow.set_opacity(0.7, start=0, end=2)
        arrows.append(arrow)

# ── RK4 particle integration ────────────────────────────────────────
def rk4_step(x, y, dt):
    """One RK4 step of the velocity field."""
    u1, v1 = velocity_field(x, y)
    u2, v2 = velocity_field(x + dt / 2 * u1, y + dt / 2 * v1)
    u3, v3 = velocity_field(x + dt / 2 * u2, y + dt / 2 * v2)
    u4, v4 = velocity_field(x + dt * u3, y + dt * v3)
    nx = x + dt / 6 * (u1 + 2 * u2 + 2 * u3 + u4)
    ny = y + dt / 6 * (v1 + 2 * v2 + 2 * v3 + v4)
    return nx, ny

sim_dt = 0.005
particle_duration = 10.0  # seconds of animation time for particles (2s to 12s)
sim_time = 15.0           # how much abstract time to integrate (scaled by speed)
speed_factor = 1.5        # map animation time to simulation time
n_sim_steps = int(sim_time / sim_dt)

# Particle seed positions — distributed around the field
seed_positions = []
# Ring of particles around the vortex pair
for angle_deg in range(0, 360, 18):  # 20 particles in a ring
    angle = math.radians(angle_deg)
    r = 3.5
    seed_positions.append((r * math.cos(angle), r * math.sin(angle)))

# Extra particles near the vortex centers for interesting spiraling
for offset in [(-1.0, 0.5), (-1.0, -0.5), (1.0, 0.5), (1.0, -0.5),
               (0.0, 1.5), (0.0, -1.5), (-3.0, 2.0), (3.0, -2.0)]:
    seed_positions.append(offset)

# Precompute all particle trajectories
particle_trajs = []
for x0, y0 in seed_positions:
    traj = [(x0, y0)]
    x, y = x0, y0
    for _ in range(n_sim_steps):
        x, y = rk4_step(x, y, sim_dt)
        # Clamp to keep particles in view
        if abs(x) > 9 or abs(y) > 6:
            break
        traj.append((x, y))
    # Convert to SVG coordinates
    svg_traj = [to_svg(px, py) for px, py in traj]
    if len(svg_traj) > 5:  # only keep trajectories with enough points
        particle_trajs.append(svg_traj)

# ── Particle dots and trail paths ────────────────────────────────────
# Particle colors: cycle through a warm-cool palette
particle_colors = color_gradient(['#FF6B6B', '#FC6255', '#FFD700', '#58C4DD',
                                   '#83C167', '#BB77FF'], n=len(particle_trajs))

particle_start_time = 2.0  # particles begin moving at t=2s

dots = []
trails = []
for i, svg_traj in enumerate(particle_trajs):
    color = particle_colors[i % len(particle_colors)]
    total_pts = len(svg_traj)

    # Dot that follows the trajectory
    dot = Dot(r=4, cx=svg_traj[0][0], cy=svg_traj[0][1],
              fill=color, stroke_width=0, creation=0)
    dot.set_opacity(0, start=0)
    dot.set_opacity(1, start=particle_start_time, end=particle_start_time + 0.3)

    def _make_head_fn(pts, total, p_start=particle_start_time):
        def _head(t):
            elapsed = t - p_start
            if elapsed <= 0:
                return pts[0]
            frac = min(elapsed * speed_factor / sim_time, 1.0)
            idx = min(int(frac * (total - 1)), total - 1)
            return pts[idx]
        return _head

    dot.c.set_onward(0, _make_head_fn(svg_traj, total_pts))

    # Trail path that grows behind the particle
    trail = Path('', stroke=color, stroke_width=1.8, stroke_opacity=0.6,
                 fill_opacity=0, creation=0)
    trail.set_opacity(0, start=0)
    trail.set_opacity(1, start=particle_start_time, end=particle_start_time + 0.3)

    def _make_trail_fn(pts, total, p_start=particle_start_time):
        def _trail_d(t):
            elapsed = t - p_start
            if elapsed <= 0:
                return ''
            frac = min(elapsed * speed_factor / sim_time, 1.0)
            n = min(int(frac * (total - 1)), total - 1)
            if n < 1:
                return ''
            # Subsample for performance (max ~400 points per path)
            step = max(1, n // 400)
            d = f'M{pts[0][0]:.1f},{pts[0][1]:.1f}'
            for j in range(step, n + 1, step):
                d += f'L{pts[j][0]:.1f},{pts[j][1]:.1f}'
            return d
        return _trail_d

    trail.d.set_onward(0, _make_trail_fn(svg_traj, total_pts))

    dots.append(dot)
    trails.append(trail)

# ── Vortex center markers ────────────────────────────────────────────
v1_svg = to_svg(vortex1[0], vortex1[1])
v2_svg = to_svg(vortex2[0], vortex2[1])

marker1 = Circle(r=8, cx=v1_svg[0], cy=v1_svg[1],
                 fill_opacity=0, stroke='#FF6B6B', stroke_width=2,
                 stroke_dasharray='4 4', creation=0)
marker2 = Circle(r=8, cx=v2_svg[0], cy=v2_svg[1],
                 fill_opacity=0, stroke='#58C4DD', stroke_width=2,
                 stroke_dasharray='4 4', creation=0)
marker1.fadein(1, 2)
marker2.fadein(1, 2)

# Rotation sense indicators
rot_label1 = Text(text='\u21ba', x=v1_svg[0], y=v1_svg[1] + 30,
                  font_size=24, fill='#FF6B6B', stroke_width=0,
                  text_anchor='middle', creation=0)
rot_label2 = Text(text='\u21bb', x=v2_svg[0], y=v2_svg[1] + 30,
                  font_size=24, fill='#58C4DD', stroke_width=0,
                  text_anchor='middle', creation=0)
rot_label1.fadein(1, 2)
rot_label2.fadein(1, 2)

# ── Title and labels ────────────────────────────────────────────────
title = Text(text='2D Vector Field: Double Vortex', x=960, y=50,
             font_size=42, fill='#fff', stroke_width=0,
             text_anchor='middle', creation=0)
title.fadein(0, 1)

subtitle = Text(text='Particle Streamlines via RK4 Integration',
                x=960, y=95, font_size=22, fill='#888', stroke_width=0,
                text_anchor='middle', creation=0)
subtitle.fadein(0.3, 1.3)

# Field equation labels
eq1 = Text(text='V(x,y) = \u03a3 \u0393\u1d62 / (2\u03c0r\u00b2) \u00d7 (-\u0394y, \u0394x)',
           x=130, y=1000, font_size=20, fill='#aaa', stroke_width=0,
           text_anchor='start', creation=0)
eq2 = Text(text='\u0393\u2081 = +8.0 (CCW)     \u0393\u2082 = \u22128.0 (CW)',
           x=130, y=1030, font_size=18, fill='#777', stroke_width=0,
           text_anchor='start', creation=0)
eq3 = Text(text='Softening radius \u03b5 = 0.4',
           x=130, y=1055, font_size=16, fill='#666', stroke_width=0,
           text_anchor='start', creation=0)
eq1.fadein(0.5, 1.5)
eq2.fadein(0.8, 1.8)
eq3.fadein(1.0, 2.0)

# Color legend
legend_title = Text(text='|V| magnitude', x=1700, y=980,
                    font_size=16, fill='#aaa', stroke_width=0,
                    text_anchor='middle', creation=0)
legend_title.fadein(1, 2)

# Color bar using small rectangles
legend_rects = []
bar_height = 120
bar_width = 14
bar_x = 1693
bar_y_top = 1000
for k in range(20):
    frac = k / 19
    ci = min(int(frac * 255), 255)
    ry = bar_y_top + (1 - frac) * bar_height  # high magnitude at top
    rect = Rectangle(x=bar_x, y=ry, width=bar_width, height=bar_height / 20 + 1,
                     fill=palette[ci], stroke_width=0, creation=0)
    rect.fadein(1, 2)
    legend_rects.append(rect)

legend_fast = Text(text='fast', x=bar_x + bar_width + 8, y=bar_y_top + 5,
                   font_size=14, fill='#aaa', stroke_width=0,
                   text_anchor='start', creation=0)
legend_slow = Text(text='slow', x=bar_x + bar_width + 8, y=bar_y_top + bar_height + 5,
                   font_size=14, fill='#aaa', stroke_width=0,
                   text_anchor='start', creation=0)
legend_fast.fadein(1, 2)
legend_slow.fadein(1, 2)

# "Particles released" annotation
release_label = Text(text='Particles released \u2192', x=300, y=520,
                     font_size=20, fill='#FFD700', stroke_width=0,
                     text_anchor='start', creation=0)
release_label.fadein(1.8, 2.5)
release_label.fadeout(4.0, 4.5)

# ── Assemble ─────────────────────────────────────────────────────────
canvas.add(*arrows)
canvas.add(*trails)
canvas.add(*dots)
canvas.add(marker1, marker2, rot_label1, rot_label2)
canvas.add(title, subtitle, eq1, eq2, eq3)
canvas.add(legend_title, *legend_rects, legend_fast, legend_slow)
canvas.add(release_label)

canvas.browser_display(start=args.start or 0, end=args.end or T,
                           fps=args.fps, port=args.port)
